server {
    listen 80;
    server_name localhost;

    # Directorio donde Vite/React deja los archivos estáticos
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy inverso: Redirige las llamadas al Gateway
    # Cualquier petición a http://localhost/api/... se enviará al Gateway
    location /api/ {
        # Importante: El nombre 'gateway-service' debe ser el mismo que el --name del contenedor
        proxy_pass http://gateway-service:4040/; 
        
        # Cabeceras estándar para que el backend sepa quién hace la petición
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Configuración para evitar problemas de timeout en peticiones largas
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
    }

    # Manejo de errores (Opcional pero recomendado)
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}